=== pdashchynski/solvd.laba-bank/src/main/resources/xml/bank.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="bank">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="accounts" type="AccountsType"/>
                <xs:element name="addresses" type="AddressesType"/>
                <xs:element name="cards" type="CardsType"/>
                <xs:element name="clients" type="ClientsType"/>
                <xs:element name="persons" type="PersonsType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="AccountType">
        <xs:sequence>
            <xs:element name="id" type="xs:integer"/>
            <xs:element name="fromDate" type="xs:date"/>
            <xs:element name="toDate" type="xs:date"/>
            <xs:element name="balance" type="xs:integer"/>
            <xs:element name="currency" type="xs:string"/>
            <xs:element name="clientId" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AccountsType">
        <xs:sequence>
            <xs:element name="account" type="AccountType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AddressType">
        <xs:sequence>
            <xs:element name="id" type="xs:integer"/>
            <xs:element name="country" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="postalCode" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AddressesType">
        <xs:sequence>
            <xs:element name="address" type="AddressType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CardType">
        <xs:sequence>
            <xs:element name="id" type="xs:integer"/>
            <xs:element name="fromDate" type="xs:date"/>
            <xs:element name="toDate" type="xs:date"/>
            <xs:element name="type" type="xs:string"/>
            <xs:element name="accountId" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CardsType">
        <xs:sequence>
            <xs:element name="card" type="CardType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ClientType">
        <xs:sequence>
            <xs:element name="id" type="xs:integer"/>
            <xs:element name="personsId" type="xs:integer"/>
            <xs:element name="status" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ClientsType">
        <xs:sequence>
            <xs:element name="client" type="ClientType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PersonType">
        <xs:sequence>
            <xs:element name="id" type="xs:integer"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="middleName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="age" type="xs:integer"/>
            <xs:element name="dateOfBirth" type="xs:date"/>
            <xs:element name="gender" type="xs:string"/>
            <xs:element name="addressesId" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PersonsType">
        <xs:sequence>
            <xs:element name="person" type="PersonType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== pdashchynski/solvd.laba-bank/src/main/resources/xml/bank.xml
<?xml version="1.0" encoding="UTF-8"?>
<bank xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bank.xsd">
    <accounts>
        <account>
            <id>4</id>
            <fromDate>2016-06-16</fromDate>
            <toDate>2026-06-16</toDate>
            <balance>5000</balance>
            <currency>USD</currency>
            <clientId>3</clientId>
        </account>

        <account>
            <id>5</id>
            <fromDate>2018-08-18</fromDate>
            <toDate>2028-08-18</toDate>
            <balance>500</balance>
            <currency>USD</currency>
            <clientId>1</clientId>
        </account>
    </accounts>

    <addresses>
        <address>
            <id>6</id>
            <country>Sweden</country>
            <city>Malmo</city>
            <postalCode>211 10</postalCode>
        </address>

        <address>
            <id>7</id>
            <country>Spain</country>
            <city>Madrid</city>
            <postalCode>28001</postalCode>
        </address>
    </addresses>

    <cards>
        <card>
            <id>5</id>
            <fromDate>2016-06-16</fromDate>
            <toDate>2026-06-16</toDate>
            <type>Credit</type>
            <accountId>1</accountId>
        </card>

        <card>
            <id>6</id>
            <fromDate>2016-06-16</fromDate>
            <toDate>2026-06-16</toDate>
            <type>Debit</type>
            <accountId>1</accountId>
        </card>
    </cards>

    <clients>
        <client>
            <id>4</id>
            <personsId>7</personsId>
            <status>VIP</status>
        </client>

        <client>
            <id>5</id>
            <personsId>8</personsId>
            <status>VIP</status>
        </client>
    </clients>

    <persons>
        <person>
            <id>7</id>
            <firstName>Olof</firstName>
            <middleName></middleName>
            <lastName>Mellberg</lastName>
            <age>46</age>
            <dateOfBirth>1977-09-03</dateOfBirth>
            <gender>Male</gender>
            <addressesId>8</addressesId>
        </person>

        <person>
            <id>8</id>
            <firstName>Jose</firstName>
            <middleName>Manuel</middleName>
            <lastName>Reina</lastName>
            <age>41</age>
            <dateOfBirth>1982-08-31</dateOfBirth>
            <gender>Male</gender>
            <addressesId>9</addressesId>
        </person>
    </persons>
</bank>
